name: Send LINE Message

on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install

    - name: Set dotenv
      run: |
        touch .env
        echo "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" >> .env
        echo "LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }}" >> .env
        echo "LINE_USER_ID=${{ secrets.LINE_USER_ID }}" >> .env
        echo "LINE_CHANNEL_ID=${{ secrets.LINE_CHANNEL_ID }}" >> .env

    - name: Send message
      run: bundle exec ruby src/send_line_message.rb
